{
 "title": "Nextcloud",
 "tags": [
  "nextcloud",
  "logs"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Nextcloud Container Logs",
   "type": "logs",
   "description": "Logs from the Nextcloud application pod",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"loki.source.kubernetes.nextcloud_app\"}"
    }
   ]
  },
  {
   "title": "Nextcloud Database Container Logs",
   "type": "logs",
   "description": "Logs from the Nextcloud database pod",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{job=\"loki.source.kubernetes.nextcloud_db\"}"
    }
   ]
  },
  {
   "title": "Nextcloud Redis Container Logs",
   "type": "logs",
   "description": "Logs from the Nextcloud redis pod",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{job=\"loki.source.kubernetes.nextcloud_redis\"}"
    }
   ]
  },
  {
   "title": "Nextcloud Cron Container Logs",
   "type": "logs",
   "description": "Logs from the Nextcloud cron pod",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{job=\"loki.source.kubernetes.nextcloud_cron\"}"
    }
   ]
  }
 ]
}