{
 "title": "Cert Manager",
 "tags": [
  "cert-manager",
  "logs"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Cert Manager Controller Container Logs",
   "type": "logs",
   "description": "Logs from the Cert Manager Controller application pod",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"loki.source.kubernetes.cert_manager_controller\"}"
    }
   ]
  },
  {
   "title": "Cert Manager Webhook Container Logs",
   "type": "logs",
   "description": "Logs from Cert Manager Webhook application pod",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"loki.source.kubernetes.cert_manager_webhook\"}"
    }
   ]
  },
  {
   "title": "Cert Manager CaInjector Container Logs",
   "type": "logs",
   "description": "Logs from the Cert Manager CaInjector application pod",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"loki.source.kubernetes.cert_manager_cainjector\"}"
    }
   ]
  }
 ]
}