{
 "title": "Flux System",
 "tags": [
  "flux",
  "logs",
  "flux-system"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Helm Controller Container Logs",
   "type": "logs",
   "description": "Logs from the Helm Controller application pod",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"flux-system\", pod=~\"helm-controller.*\"}"
    }
   ]
  },
  {
   "title": "Kustomize Controller Container Logs",
   "type": "logs",
   "description": "Logs from the Kustomize Controller application pod",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{namespace=\"flux-system\", pod=~\"kustomize-controller.*\"}"
    }
   ]
  },
  {
   "title": "Notfication Controller Container Logs",
   "type": "logs",
   "description": "Logs from the Notfication Controller application pod",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{namespace=\"flux-system\", pod=~\"notification-controller.*\"}"
    }
   ]
  },
  {
   "title": "Source Controller Container Logs",
   "type": "logs",
   "description": "Logs from the Source Controller application pod",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{namespace=\"flux-system\", pod=~\"source-controller.*\"}"
    }
   ]
  },
  {
   "title": "Sealed Secrets Controller Container Logs",
   "type": "logs",
   "description": "Logs from the Sealed Secrets Controller application pod",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{namespace=\"flux-system\", pod=~\"sealed-secrets.*\"}"
    }
   ]
  }
 ]
}