{
 "title": "Loki",
 "tags": [
  "loki",
  "logs",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Loki Container Logs",
   "type": "logs",
   "description": "Logs from the Loki application pod",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"loki.source.kubernetes.loki_app\"}"
    }
   ]
  },
  {
   "title": "Loki Canary Container Logs",
   "type": "logs",
   "description": "Logs from the Loki Canary application pod",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{job=\"loki.source.kubernetes.loki_canary\"}"
    }
   ]
  },
  {
   "title": "Loki Gateway Container Logs",
   "type": "logs",
   "description": "Logs from the Loki Gateway application pod",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"loki.source.kubernetes.loki_gateway\"}"
    }
   ]
  },
  {
   "title": "Loki Chunks Cache Container Logs",
   "type": "logs",
   "description": "Logs from the Loki Chunks Cache application pod",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{job=\"loki.source.kubernetes.loki_chunks_cache\"}"
    }
   ]
  },
  {
   "title": "Loki Results Cache Container Logs",
   "type": "logs",
   "description": "Logs from the Loki Results Cache application pod",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{job=\"loki.source.kubernetes.loki_results_cache\"}"
    }
   ]
  }
 ]
}